### ISSUE TITLE
copy_frame missing attributes which are defaults in source matrix

### ISSUE THREAD

**Issue by timtianyang** [ebroecker/canmatrix#430]
test case:

The following attribute and default values will not get picked up unless some frames have specified values for the attribute.

For example, the following will get skipped:
```
BA_DEF_ BO_ "GenMsgDelayTime" INT 0 65535;
BA_DEF_DEF_ "GenMsgDelayTime" 0 ;
```
unless a message has non default value assigned:
`BA_ "GenMsgDelayTime" BO_ 513 100 ;`

**Comment by ebroecker** [comment]
please try branch `iss427`

**Comment by timtianyang** [comment]
I think iss427 fixes the white space issue, but defaults are still missing.

**Comment by ebroecker** [comment]
well - it is fixed also, but handling of default values is different...
I'll update the example-code in issue #428 to show how to handle with 
default values, ...

**Comment by timtianyang** [comment]
Thanks for the example. I think issue #430 is still persists. It's not about filtering out default values. It's about copying frames, but some default values are not copied, unless specified with a non default value.

**Comment by ebroecker** [comment]
should be fixed now. (in branch `iss427`)

**Comment by timtianyang** [comment]
thanks for the fix!

**Comment by ebroecker** [comment]
@timtianyang 
Thanks for reporting all these bugs

**Comment by ebroecker** [comment]
sometimes it happens that "None" is exported as attribute.
